import numpy as np
a=np.array([[0,0],[0,0]])
b=np.array([[0,0],[0,1]])
c=np.array([[0,0],[1,0]])
d=np.array([[0,0],[1,1]])
e=np.array([[0,1],[0,0]])
f=np.array([[0,1],[0,1]])
g=np.array([[0,1],[1,0]])
h=np.array([[0,1],[1,1]])
i=np.array([[1,0],[0,0]])
j=np.array([[1,0],[0,1]])
k=np.array([[1,0],[1,0]])
l=np.array([[1,0],[1,1]])
m=np.array([[1,1],[0,0]])
n=np.array([[1,1],[0,1]])
o = np.array([[1, 1], [1, 0]])
p = np.array([[1, 1], [1, 1]])

print("Det of a is ",np.linalg.det(a))
print("Det of b is ",np.linalg.det(b))
print("Det of c is ",np.linalg.det(c))
print("Det of d is ",np.linalg.det(d))
print("Det of e is ",np.linalg.det(e))
print("Det of f is ",np.linalg.det(f))
print("Det of g is ",np.linalg.det(g))
print("Det of h is ",np.linalg.det(h))
print("Det of i is ",np.linalg.det(i))
print("Det of j is ",np.linalg.det(j))
print("Det of k is ",np.linalg.det(k))
print("Det of l is ",np.linalg.det(l))
print("Det of m is ",np.linalg.det(m))
print("Det of n is ",np.linalg.det(n))
print("Det of o is ",np.linalg.det(o))
print("Det of p is ",np.linalg.det(p))